name: Static Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: Kesin11/actions-timeline@v1
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and Start Containers
      run: docker compose up -d --build

    - name: Install Dependencies
      run: docker compose exec app bash -c "/etc/poetry/bin/poetry install"
      working-directory: app

    - name: Test with Pytest and Coverage
      run: docker compose exec app bash -c "/etc/poetry/bin/poetry run coverage run pytest"
      working-directory: app
